{
    "ParentLink": {
        "Property": "qc_ATTACHMENTS",
        "Target": {
            "EntitySet": "QC_HEADER",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "sheetNo": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:sheetNo/#Value",
        "sectionNo": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:sectionNo/#Value",
        "question": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:question/#Value",
        "mimeType": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:mimeType/#Value",
        "name": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:name/#Value",
        "file": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:file/#Value",
        "size": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:size/#Value",
        "qC_HEADER_SNORKEL_NO": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:qC_HEADER_SNORKEL_NO/#SelectedValue",
        "qC_HEADER_CUSTOMER_NAME": "#Page:QC_HEADER_CreateATTACHMENTS/#Control:qC_HEADER_CUSTOMER_NAME/#Value"
    },
    "Target": {
        "EntitySet": "ATTACHMENTS",
        "Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}