{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/TRL_Snorkel_Digitization_TSL/Pages/TRL_Snorkel_CAP_SRV_QC_ITEM/QC_ITEM_Edit.page",
    "_Type": "Action.Type.Navigation"
}