{
    "PopoverItems": [{
            "Title": "Add ATTACHMENTS",
            "OnPress": "/TRL_Snorkel_Digitization_TSL/Actions/TRL_Snorkel_CAP_SRV/QC_ITEM/NavToQC_ITEM_CreateATTACHMENTS.action"
        },
        {
            "Title": "Add Test_Table",
            "OnPress": "/TRL_Snorkel_Digitization_TSL/Actions/TRL_Snorkel_CAP_SRV/QC_ITEM/NavToQC_ITEM_CreateTest_Table.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/TRL_Snorkel_Digitization_TSL/Rules/TRL_Snorkel_CAP_SRV/QC_ITEM/QC_ITEM_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}