{
    "CreateLinks": [],
    "OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "name": "#Page:QC_HEADER_FILES_Create/#Control:name/#Value",
        "mimeType": "#Page:QC_HEADER_FILES_Create/#Control:mimeType/#Value",
        "file": "#Page:QC_HEADER_FILES_Create/#Control:file/#Value",
        "size": "#Page:QC_HEADER_FILES_Create/#Control:size/#Value",
        "SNORKEL_NO": "#Page:QC_HEADER_FILES_Create/#Control:SNORKEL_NO/#SelectedValue",
        "CUSTOMER_NAME": "#Page:QC_HEADER_FILES_Create/#Control:CUSTOMER_NAME/#Value"
    },
    "Target": {
        "EntitySet": "QC_HEADER_FILES",
        "Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}