{
  "_Type": "Action.Type.ODataService.CreateEntity",
  "ActionResult": {
    "_Name": "AttachmentCreate135"
  },
  "Target": {
    "Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
    "EntitySet": "ATTACHMENTS"
  },
  "Properties": {
    "question": "{question}",
    "mimeType": "{mimeType}",
    "name": "{name}",
    "file": "{file}",
    "size": "{size}",
    "qC_HEADER_SNORKEL_NO": "{qC_HEADER_SNORKEL_NO}"
  }
}
