{
    "Animated": true,
    "Duration": 2,
    "Message": "Entity deleted",
    "Icon": "",
    "IsIconHidden": false,
    "NumberOfLines": 2,
    "OnSuccess": "/TRL_Snorkel_Digitization_TSL/Actions/CloseModalPage_Complete.action",
    "_Type": "Action.Type.ToastMessage"
}