{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "HeaderCreate"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/TRL_Snorkel_CAP_SRV/Service/InitializeOnlineFailureMessage.action",
	"OnSuccess": "/TRL_Snorkel_Digitization_TSL/Rules/Section1Visible.js",
	"OnSuccessLog": {
		"Level": "Info",
		"Message": "Header Configured"
	},
	"OnInvalidLog": {
		"Message": "Please Fill All Fields To Proceed!",
		"Level": "Error"
	},
	"OnFailureLog": {
		"Message": "Please Fill All Fields To Proceed!",
		"Level": "Error"
	},
	"ShowActivityIndicator": true,
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_HEADER"
	},
	"Properties": {
		"CUSTOMER_NAME": "#Page:SnorkelInstallation/#Control:Company/#SelectedValue",
		"SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value",
		"DATE_ENDED": "#Page:SnorkelInstallation/#Control:EndDate/#Value",
		"DATE_STARTED": "#Page:SnorkelInstallation/#Control:StartDate/#Value",
		"DRAFT_FLAG": true,
		"TYPE": "#Page:SnorkelInstallation/#Control:TypeList/#SelectedValue",
		"CHECKER": "#Page:SnorkelInstallation/#Control:Checker/#SelectedValue",
		"PRODUCTION_NO": "#Page:SnorkelInstallation/#Control:ProductionNo/#Value"
	}
}