{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "Nav2Sheet4"
	},
	"PageToOpen": "/TRL_Snorkel_Digitization_TSL/Pages/SnorkelInstallation4.page",
	"BackStackVisible": true,
	"ClearHistory": false
}