{
  "_Type": "Action.Type.ODataService.CreateEntity",
  "ActionResult": {
    "_Name": "QCCastingCreate"
  },
  "Target": {
    "Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
    "EntitySet": "QC_CASTING"
  },
  "Properties": {
    "qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value",
    "brickBrandName": "#Page:FinalInspection/#Control:BrickBrand/#Value",
    "brickLotNo": "#Page:FinalInspection/#Control:BrickLot/#Value",
    "castableBrandName": "#Page:FinalInspection/#Control:CastableBrand/#Value",
    "castableLotNo": "#Page:FinalInspection/#Control:CastableLot/#Value",
    "addedWaterPercent": "#Page:FinalInspection/#Control:AddedWater/#Value",
    "mixingTimeMin": "#Page:FinalInspection/#Control:MixingTime/#Value",
    "argonPipeFlowA": "#Page:FinalInspection/#Control:Flow_A/#Value",
    "argonPipeFlowB": "#Page:FinalInspection/#Control:Flow_B/#Value",
    "argonPipeFlowC": "#Page:FinalInspection/#Control:Flow_C/#Value",
    "argonPipeFlowD": "#Page:FinalInspection/#Control:Flow_D/#Value",
    "argonPipeFlowE": "#Page:FinalInspection/#Control:Flow_E/#Value",
    "argonPipeFlowF": "#Page:FinalInspection/#Control:Flow_F/#Value",
    "argonPipeFlowG": "#Page:FinalInspection/#Control:Flow_G/#Value",
    "argonPipeFlowH": "#Page:FinalInspection/#Control:Flow_H/#Value",
    "argonPipeFlowI": "#Page:FinalInspection/#Control:Flow_I/#Value",
    "argonPipeFlowJ": "#Page:FinalInspection/#Control:Flow_J/#Value",
    "argonPipeFlowK": "#Page:FinalInspection/#Control:Flow_K/#Value",
    "argonPipeFlowL": "#Page:FinalInspection/#Control:Flow_L/#Value",
    "remarkA": "#Page:FinalInspection/#Control:SectionFinalCastingRemarkStatusFormARemarks/#Value",
    "checkA": "#Page:FinalInspection/#Control:SectionFinalCastingRemarkStatusFormACheck/#SelectedValue",
    "remarkB": "#Page:FinalInspection/#Control:SectionFinalCastingRemarkStatusFormBRemark/#Value",
    "checkB": "#Page:FinalInspection/#Control:SectionFinalCastingRemarkStatusFormBCheck/#SelectedValue",
    "remarks": "",
    "checkStatus": "",
    "type": "Casting"
  }
}
