{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "QCCheckCreate"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_CHECK"
	},
	"Properties": {
		"curingTimeHr": "#Page:FinalInspection/#Control:CuringTime/#Value",
		"dryingTimeHr": "#Page:FinalInspection/#Control:DryingTime(hr)/#Value",
		"dryingFurnace": "#Page:FinalInspection/#Control:DryingFurnace(MT)/#Value",
		"afterDrying": "#Page:FinalInspection/#Control:AfterDryingPreAssembly/#Value",
		"preAssembly": "#Page:FinalInspection/#Control:AfterDryingPreAssembly/#Value",
		"argonPipeWelding": "#Page:FinalInspection/#Control:SectionFinalCheckaragon/#SelectedValue",
		"snorkelLotNo": "#Page:FinalInspection/#Control:SnorkelLot/#Value",
		"stencilingMarking": "#Page:FinalInspection/#Control:StencilingMarking/#Value",
		"remarkA": "#Page:FinalInspection/#Control:SectionFinalCheckRemarkASnorkelLotRemark/#Value",
		"checkA": "#Page:FinalInspection/#Control:SectionFinalCheckRemarkACheck/#SelectedValue",
		"remarkB": "#Page:FinalInspection/#Control:SectionFinalCheckRemarkBRemark/#Value",
		"checkB": "#Page:FinalInspection/#Control:SectionFinalCheckRemarkBcheck/#SelectedValue",
		"type": "FinalCheck",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}