{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section132Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation4/#Control:Section132Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation4/#Control:Section132DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation4/#Control:Section132InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation4/#Control:Section132Method/#Value",
		"QUESTION": "13.2 Center position of the ring brick  *8",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}