{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section162TestCreate3"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"fluidity": "#Page:SnorkelInstallation5/#Control:Section152FludityOfCastable3/#SelectedValue",
		"powderweight": "#Page:SnorkelInstallation5/#Control:Section152PowerWeight3/#Value",
		"remark": "#Page:SnorkelInstallation5/#Control:Section152Remark3/#Value",
		"testname": "*10 Actual situation for mixing the outer castable",
		"vibration": "#Page:SnorkelInstallation5/#Control:Section152AddingVibration3/#SelectedValue",
		"watercasting": "#Page:SnorkelInstallation5/#Control:Section152WaterCasting3/#Value",
		"batchNo": "#Page:SnorkelInstallation5/#Control:Section152TestBatchNo3/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}