{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section102TestCreate4"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"fluidity": "#Page:SnorkelInstallation2/#Control:Section102FludityOfCastable4/#SelectedValue",
		"powderweight": "#Page:SnorkelInstallation2/#Control:Section102PowerWeight4/#Value",
		"remark": "#Page:SnorkelInstallation2/#Control:Section102Remark4/#Value",
		"testname": "*4 Actual situation for mixing the outer castable",
		"vibration": "#Page:SnorkelInstallation2/#Control:Section102AddingVibration4/#SelectedValue",
		"watercasting": "#Page:SnorkelInstallation2/#Control:Section102WaterCasting4/#Value",
		"batchNo": "#Page:SnorkelInstallation2/#Control:Section102TestBatchNo4/#Value",
		"QUESTION": "10.2 The gap between the top of the casting mould to the top face of casting    *5",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}