{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section141TestOutletCreate3"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	}
	,
	"Properties": {
		"fluidity": "#Page:SnorkelInstallation4/#Control:Section142FludityOfCastable3/#SelectedValue",
		"powderweight": "#Page:SnorkelInstallation4/#Control:Section142PowerWeight3/#Value",
		"remark": "#Page:SnorkelInstallation4/#Control:Section142Remark3/#Value",
		"testname": "*9  Actual situation for mixing the outer castable",
		"vibration": "#Page:SnorkelInstallation4/#Control:Section142AddingVibration3/#SelectedValue",
		"watercasting": "#Page:SnorkelInstallation4/#Control:Section142WaterCasting3/#Value",
		"batchNo": "#Page:SnorkelInstallation4/#Control:Section142TestBatchNo3/#Value",
				"QUESTION": "14.2 The gap between the top of brick surface   to the top face of casting    *10",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}