{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section111TestCreate1"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"actualvalue": "#Page:SnorkelInstallation3/#Control:Section111TestActualValue4/#Value",
		"date": "#Page:SnorkelInstallation3/#Control:Section111TestDate4/#Value",
		"method": "#Page:SnorkelInstallation3/#Control:Section111TestMethod4/#Value",
		"specification": "#Page:SnorkelInstallation3/#Control:Section111TestSpecification4/#Value",
		"testname": "*6 MOR test result",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}