{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section152Test2CreateA"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"actualvalue": "#Page:SnorkelInstallation5/#Control:Section152TestActualGapA/#Value",
		"method": "#Page:SnorkelInstallation5/#Control:Section152TestMethodA/#Value",
		"position": "#Page:SnorkelInstallation5/#Control:Section152TestPositionGapA/#Value",
		"tolerance": "#Page:SnorkelInstallation5/#Control:Section152TestToleranceA/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value",
		"testname": "*11 The gap between the top of brick surface to the top face of castable"
	}
}