{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section184Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation6/#Control:Section184Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation6/#Control:Section184DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation6/#Control:Section184InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation6/#Control:Section184Method/#Value",
		"QUESTION": "18.4 Installation of the removal equipment with automatically for the hanging hooks ",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}