{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section102TestCreate1"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"fluidity": "#Page:SnorkelInstallation2/#Control:Section102FludityOfCastable1/#SelectedValue",
		"powderweight": "#Page:SnorkelInstallation2/#Control:Section102PowerWeight1/#Value",
		"remark": "#Page:SnorkelInstallation2/#Control:Section102Remark1/#Value",
		"testname": "*4 Actual situation for mixing the outer castable",
		"vibration": "#Page:SnorkelInstallation2/#Control:Section102AddingVibration1/#Value",
		"watercasting": "#Page:SnorkelInstallation2/#Control:Section102WaterCasting1/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}