{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section202Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation7/#Control:Section202Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation7/#Control:Section202DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation7/#Control:Section202InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation7/#Control:Section202Method/#Value",
		"QUESTION": "20.2 Appearance",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}