{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section193Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation6/#Control:Section193Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation6/#Control:Section193DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation6/#Control:Section193InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation6/#Control:Section193Method/#Value",
		"QUESTION": "19.3 Putting the mark with clearly *12",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}