{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section141CreateOutlet"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation4/#Control:Section141Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation4/#Control:Section141DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation4/#Control:Section141InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation4/#Control:Section141Method/#Value",
		"QUESTION": "14.1 Situation of Mixing for gap filling castable  'HC-H111B'  *9",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}