{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section91TestCreateB"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"ff1": "#Page:SnorkelInstallation2/#Control:Section91FF2/#Value",
		"ff2": "#Page:SnorkelInstallation2/#Control:Section91FF22/#Value",
		"remark": "#Page:SnorkelInstallation2/#Control:Section91TestRemark2/#Value",
		"settleduration": "#Page:SnorkelInstallation2/#Control:Section91SettingTime2/#Value",
		"testname": "*3 Inspection result of outer castable workablity",
		"tf1": "#Page:SnorkelInstallation2/#Control:Section91TF2/#Value",
		"tf2": "#Page:SnorkelInstallation2/#Control:Section91TF22/#Value",
		"watercasting": "#Page:SnorkelInstallation2/#Control:Section91TestWaterCasteing2/#Value",
		"batchNo": "#Page:SnorkelInstallation2/#Control:Section91TestBatchNo2/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}