{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section141TestOutletCreate4"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	}
	,
	"Properties": {
		"fluidity": "#Page:SnorkelInstallation4/#Control:Section142FludityOfCastable4/#SelectedValue",
		"powderweight": "#Page:SnorkelInstallation4/#Control:Section142PowerWeight4/#Value",
		"remark": "#Page:SnorkelInstallation4/#Control:Section142Remark4/#Value",
		"testname": "*9  Actual situation for mixing the outer castable",
		"vibration": "#Page:SnorkelInstallation4/#Control:Section142AddingVibration4/#SelectedValue",
		"watercasting": "#Page:SnorkelInstallation4/#Control:Section142WaterCasting4/#Value",
		"batchNo": "#Page:SnorkelInstallation4/#Control:Section142TestBatchNo4/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}