{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section201Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation7/#Control:Section201Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation7/#Control:Section201DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation7/#Control:Section201InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation7/#Control:Section201Method/#Value",
		"QUESTION": "20.1 Dimension",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}