{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section121Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation3/#Control:Section121Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation3/#Control:Section121DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation3/#Control:Section121InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation3/#Control:Section121Method/#Value",
		"QUESTION": "12.1 Confirmation of the protrusion of Ar pipe ",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}