{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section91TestCreateC"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"ff": "#Page:SnorkelInstallation2/#Control:Section91FF3/#Value",
		"remark": "#Page:SnorkelInstallation2/#Control:Section91TestRemark3/#Value",
		"settleduration": "#Page:SnorkelInstallation2/#Control:Section91SettingTime3/#Value",
		"testname": "*3 Inspection result of outer castable workablity",
		"tf": "#Page:SnorkelInstallation2/#Control:Section91TF3/#Value",
		"watercasting": "#Page:SnorkelInstallation2/#Control:Section91TestWaterCasteing3/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}