{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section152Test2CreateB"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"actualvalue": "#Page:SnorkelInstallation5/#Control:Section152TestActualGapB/#Value",
		"method": "#Page:SnorkelInstallation5/#Control:Section152TestMethodB/#Value",
		"position": "#Page:SnorkelInstallation5/#Control:Section152TestPositionGapB/#Value",
		"tolerance": "#Page:SnorkelInstallation5/#Control:Section152TestToleranceB/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value",
		"testname": "*11 The gap between the top of brick surface to the top face of castable"
	}
}