{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section41TestCreateD"
	},
	
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"actualvalue": "#Page:SnorkelInstallation/#Control:Section41TestActualGapD/#Value",
		"method": "#Page:SnorkelInstallation/#Control:Section41TestMethodD/#Value",
		"position": "#Page:SnorkelInstallation/#Control:Section41TestPositionGapD/#Value",
		"testname": "*1 Gap measurement between 1st ring brick and the Core Shell *(Actual Max - Actual Min) < 2mm",
		"tolerance": "#Page:SnorkelInstallation/#Control:Section41TestToleranceD/#Value",
		"QUESTION": "4.1 Result of gap measurement  *1( Uniform gap is required in the circumference)",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}