{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section162TestCreate4"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"fluidity": "#Page:SnorkelInstallation5/#Control:Section152FludityOfCastable4/#SelectedValue",
		"powderweight": "#Page:SnorkelInstallation5/#Control:Section152PowerWeight4/#Value",
		"remark": "#Page:SnorkelInstallation5/#Control:Section152Remark4/#Value",
		"testname": "*9 Actual situation for mixing the outer castable",
		"vibration": "#Page:SnorkelInstallation5/#Control:Section152AddingVibration4/#SelectedValue",
		"watercasting": "#Page:SnorkelInstallation5/#Control:Section152WaterCasting4/#Value",
		"batchNo": "#Page:SnorkelInstallation5/#Control:Section152TestBatchNo4/#Value",
		"QUESTION": "15.2 The gap between the top of brick surface  to the top face of casting  *9",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}