{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section152TestCreate1"
	},
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"fluidity": "#Page:SnorkelInstallation5/#Control:Section152FludityOfCastable1/#SelectedValue",
		"powderweight": "#Page:SnorkelInstallation5/#Control:Section152PowerWeight1/#Value",
		"remark": "#Page:SnorkelInstallation5/#Control:Section152Remark1/#Value",
		"testname": "*10 Actual situation for mixing the outer castable",
		"vibration": "#Page:SnorkelInstallation5/#Control:Section152AddingVibration1/#SelectedValue",
		"watercasting": "#Page:SnorkelInstallation5/#Control:Section152WaterCasting1/#Value",
		"batchNo": "#Page:SnorkelInstallation5/#Control:Section152TestBatchNo1/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}