{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section162CreateOutlet"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation4/#Control:Section162Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation4/#Control:Section162DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation4/#Control:Section162InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation4/#Control:Section162Method/#Value",
		"QUESTION": " 16.2 Drying time (76~80 hrs)",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}