{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section81Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/TRL_Snorkel_Digitization_TSL/Rules/Section82Visible.js",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation2/#Control:Section81Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation2/#Control:Section81DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation2/#Control:Section81InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation2/#Control:Section81Method/#Value",
		"QUESTION": "8.1 Clean up the inner surface of the mould & Coating the de-moulding oil/grease",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}