{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section41Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/TRL_Snorkel_Digitization_TSL/Rules/Section41ImageVisible.js",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation/#Control:Section41Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation/#Control:Section41DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation/#Control:Section41InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation/#Control:Section41Method/#Value",
		"QUESTION": "4.1 Result of gap measurement  *1 ( Uniform gap is required in the circumference)",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}