{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section151CreateOutlet"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation4/#Control:Section151Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation4/#Control:Section151DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation4/#Control:Section151InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation4/#Control:Section151Method/#Value",
		"QUESTION": " 15.1 Curing time   > 24Hr",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}