{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section42Create"
	},
	"OnFailure": "/TRL_Snorkel_Digitization_TSL/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/TRL_Snorkel_Digitization_TSL/Rules/Section5Visible.js",
	"Target": {
		"Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation/#Control:Section42Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation/#Control:Section42DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation/#Control:Section42InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation/#Control:Section42Method/#Value",
		"QUESTION": "4.2 Confirmation of positive dimension of lower part",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}