{
  "Type": "Action.Type.OpenDocument",
  "Name": "ShowPDFDocument",
  "Document": {
    "Name": "QCReport.pdf",
    "Content": "{{#Property:pdfBase64}}",
    "ContentType": "application/pdf",
    "Encoding": "Base64"
  }
}