{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/TRL_Snorkel_Digitization_TSL/Rules/Section1Visible.js",
	"Message": "Snorkel No: {SNORKEL_NO}",
	"Duration": 10,
	"IsIconHidden": true,
	"Animated": true
}