{
  "_Type": "Action.Type.ODataService.UpdateEntity",
  "Target": {
    "Service": "/TRL_Snorkel_Digitization_TSL/Services/TRL_Snorkel_CAP_SRV.service",
    "EntitySet": "{EntitySet}",
    "ReadLink": "{ReadLink}"
  }
  }